from dataclasses import dataclass
from swagger_codegen.api.client import ApiClient
from swagger_codegen.api.configuration import Configuration
from swagger_codegen.api.adapter.base import HttpClientAdapter


from .apis.clientes.api import ClientesApi

from .apis.instalacoes.api import InstalacoesApi

from .apis.faturas.api import FaturasApi



@dataclass
class AutogeneratedApiClient:
    configuration: Configuration
    client: ApiClient
    clientes: ClientesApi
    instalacoes: InstalacoesApi
    faturas: FaturasApi


def new_client(
    adapter: HttpClientAdapter, configuration: Configuration
) -> AutogeneratedApiClient:
    client = ApiClient(configuration=configuration, adapter=adapter)
    return AutogeneratedApiClient(
        configuration,
        client=client,
        
        clientes=ClientesApi(client, configuration),
        
        instalacoes=InstalacoesApi(client, configuration),
        
        faturas=FaturasApi(client, configuration)
        
    )